/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Shipment {
  'trackingNumber' : string,
  'destination' : string,
  'createdAt' : Time,
  'origin' : string,
  'recipient' : [] | [string],
  'events' : Array<TrackingEvent>,
}
export type Time = bigint;
export interface TrackingEvent {
  'status' : string,
  'date' : string,
  'note' : [] | [string],
  'time' : string,
  'timestamp' : Time,
  'location' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTestShipments' : ActorMethod<[], undefined>,
  'addTrackingEvent' : ActorMethod<[string, TrackingEvent], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createShipment' : ActorMethod<
    [string, string, string, [] | [string]],
    undefined
  >,
  'generateTrackingNumber' : ActorMethod<[], string>,
  'getAllShipments' : ActorMethod<[], Array<Shipment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLatestTrackingEvent' : ActorMethod<[string], TrackingEvent>,
  'getShipment' : ActorMethod<[string], Shipment>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setInitialAdmin' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];