/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TrackingEvent = IDL.Record({
  'status' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'time' : IDL.Text,
  'timestamp' : Time,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Shipment = IDL.Record({
  'trackingNumber' : IDL.Text,
  'destination' : IDL.Text,
  'createdAt' : Time,
  'origin' : IDL.Text,
  'recipient' : IDL.Opt(IDL.Text),
  'events' : IDL.Vec(TrackingEvent),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestShipments' : IDL.Func([], [], []),
  'addTrackingEvent' : IDL.Func([IDL.Text, TrackingEvent], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createShipment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'generateTrackingNumber' : IDL.Func([], [IDL.Text], []),
  'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLatestTrackingEvent' : IDL.Func([IDL.Text], [TrackingEvent], ['query']),
  'getShipment' : IDL.Func([IDL.Text], [Shipment], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setInitialAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TrackingEvent = IDL.Record({
    'status' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'time' : IDL.Text,
    'timestamp' : Time,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Shipment = IDL.Record({
    'trackingNumber' : IDL.Text,
    'destination' : IDL.Text,
    'createdAt' : Time,
    'origin' : IDL.Text,
    'recipient' : IDL.Opt(IDL.Text),
    'events' : IDL.Vec(TrackingEvent),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestShipments' : IDL.Func([], [], []),
    'addTrackingEvent' : IDL.Func([IDL.Text, TrackingEvent], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createShipment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'generateTrackingNumber' : IDL.Func([], [IDL.Text], []),
    'getAllShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLatestTrackingEvent' : IDL.Func([IDL.Text], [TrackingEvent], ['query']),
    'getShipment' : IDL.Func([IDL.Text], [Shipment], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setInitialAdmin' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };